version: '3.8'

services:
  python-container:
    build:
      context: ./python-container
    volumes:
      - ./python-container:/app
    depends_on:
      - node-container

  node-container:
    build:
      context: ./node-container
    ports:
      - "3000:3000"
    volumes:
      - ./node-container:/app
